import type { Metadata } from "next";
// import { GeistSans, GeistMono } from "@vercel/fonts";
import "./globals.css";

// const geistSans = GeistSans({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = GeistMono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://geist.vercel.app/font.css" />
      </head>
      <body className="font-sans antialiased">
        {children}
      </body>
    </html>
  );
}

